
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import theme from './theme';
import AccountMenu from '@/components/menu';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

        <AppRouterCacheProvider>
        <AccountMenu></AccountMenu>
          <ThemeProvider theme={theme}>
               {children}
            </ThemeProvider>
          
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
